//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Hell_WPF_Multipack_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_Hell_WPF_Multipack_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _ {
            get {
                object obj = ResourceManager.GetObject("_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _play_hover {
            get {
                object obj = ResourceManager.GetObject("_play_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _play_normal {
            get {
                object obj = ResourceManager.GetObject("_play_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _play_pressed {
            get {
                object obj = ResourceManager.GetObject("_play_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05b877de3962048c5d1bd7cc18d4b286.
        /// </summary>
        public static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://n.helldar.ru.
        /// </summary>
        public static string API_DEV_Address {
            get {
                return ResourceManager.GetString("API_DEV_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/wot/info.
        /// </summary>
        public static string API_DEV_Info {
            get {
                return ResourceManager.GetString("API_DEV_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /openid.html.
        /// </summary>
        public static string API_DEV_OpenID {
            get {
                return ResourceManager.GetString("API_DEV_OpenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/wot/processes.
        /// </summary>
        public static string API_DEV_Processes {
            get {
                return ResourceManager.GetString("API_DEV_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/wot/ticket.
        /// </summary>
        public static string API_DEV_Ticket {
            get {
                return ResourceManager.GetString("API_DEV_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/account/info/.
        /// </summary>
        public static string API_WOT_Account_Info {
            get {
                return ResourceManager.GetString("API_WOT_Account_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/account/list/.
        /// </summary>
        public static string API_WOT_Account_List {
            get {
                return ResourceManager.GetString("API_WOT_Account_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.worldoftanks.ru.
        /// </summary>
        public static string API_WOT_Address {
            get {
                return ResourceManager.GetString("API_WOT_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/globalwar/battles.
        /// </summary>
        public static string API_WOT_Clan_Battles {
            get {
                return ResourceManager.GetString("API_WOT_Clan_Battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/clan/info/.
        /// </summary>
        public static string API_WOT_Clan_Info {
            get {
                return ResourceManager.GetString("API_WOT_Clan_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/clan/provinces/.
        /// </summary>
        public static string API_WOT_Clan_Provinces {
            get {
                return ResourceManager.GetString("API_WOT_Clan_Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/globalwar/provinces/.
        /// </summary>
        public static string API_WOT_Global_Provinces {
            get {
                return ResourceManager.GetString("API_WOT_Global_Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /wot/auth/login/.
        /// </summary>
        public static string API_WOT_OpenID {
            get {
                return ResourceManager.GetString("API_WOT_OpenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ava {
            get {
                object obj = ResourceManager.GetObject("ava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkbox_active_checked {
            get {
                object obj = ResourceManager.GetObject("checkbox_active_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkbox_active_unchecked {
            get {
                object obj = ResourceManager.GetObject("checkbox_active_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkbox_unactive_checked {
            get {
                object obj = ResourceManager.GetObject("checkbox_unactive_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkbox_unactive_unchecked {
            get {
                object obj = ResourceManager.GetObject("checkbox_unactive_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_hover {
            get {
                object obj = ResourceManager.GetObject("close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_normal {
            get {
                object obj = ResourceManager.GetObject("close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_press {
            get {
                object obj = ResourceManager.GetObject("close_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cursor_Chrome {
            get {
                object obj = ResourceManager.GetObject("Cursor_Chrome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string Default_Lang {
            get {
                return ResourceManager.GetString("Default_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.
        /// </summary>
        public static string Default_Multipack_Type {
            get {
                return ResourceManager.GetString("Default_Multipack_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipack.
        /// </summary>
        public static string Default_Settings_Priority {
            get {
                return ResourceManager.GetString("Default_Settings_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string Developer_Feedback_Symbols {
            get {
                return ResourceManager.GetString("Developer_Feedback_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/5PR4ma.
        /// </summary>
        public static string Developer_Link_Site {
            get {
                return ResourceManager.GetString("Developer_Link_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_de {
            get {
                object obj = ResourceManager.GetObject("flag_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_en {
            get {
                object obj = ResourceManager.GetObject("flag_en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_ru {
            get {
                object obj = ResourceManager.GetObject("flag_ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Background {
            get {
                object obj = ResourceManager.GetObject("General_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Feedback_hover {
            get {
                object obj = ResourceManager.GetObject("General_Feedback_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Feedback_normal {
            get {
                object obj = ResourceManager.GetObject("General_Feedback_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Feedback_press {
            get {
                object obj = ResourceManager.GetObject("General_Feedback_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Line {
            get {
                object obj = ResourceManager.GetObject("General_Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_News_Close_hover {
            get {
                object obj = ResourceManager.GetObject("General_News_Close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_News_Close_normal {
            get {
                object obj = ResourceManager.GetObject("General_News_Close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_News_Close_pressed {
            get {
                object obj = ResourceManager.GetObject("General_News_Close_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Optimize_hover {
            get {
                object obj = ResourceManager.GetObject("General_Optimize_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Optimize_normal {
            get {
                object obj = ResourceManager.GetObject("General_Optimize_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Optimize_pressed {
            get {
                object obj = ResourceManager.GetObject("General_Optimize_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Profile_hover {
            get {
                object obj = ResourceManager.GetObject("General_Profile_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Profile_normal {
            get {
                object obj = ResourceManager.GetObject("General_Profile_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Profile_pressed {
            get {
                object obj = ResourceManager.GetObject("General_Profile_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Settings_hover {
            get {
                object obj = ResourceManager.GetObject("General_Settings_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Settings_normal {
            get {
                object obj = ResourceManager.GetObject("General_Settings_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap General_Settings_press {
            get {
                object obj = ResourceManager.GetObject("General_Settings_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Global_Background {
            get {
                object obj = ResourceManager.GetObject("Global_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon__landing {
            get {
                object obj = ResourceManager.GetObject("icon__landing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon__meeting {
            get {
                object obj = ResourceManager.GetObject("icon__meeting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon__province {
            get {
                object obj = ResourceManager.GetObject("icon__province", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protanki.
        /// </summary>
        public static string INI {
            get {
                return ResourceManager.GetString("INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ionic_Zip {
            get {
                object obj = ResourceManager.GetObject("Ionic_Zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://file.theaces.ru/mods/proupdate/update.json.
        /// </summary>
        public static string JsonUpdates {
            get {
                return ResourceManager.GetString("JsonUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap line1 {
            get {
                object obj = ResourceManager.GetObject("line1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/Wlrh9F.
        /// </summary>
        public static string LinkNewsAll {
            get {
                return ResourceManager.GetString("LinkNewsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/LXaU7T.
        /// </summary>
        public static string LinkVideoAll {
            get {
                return ResourceManager.GetString("LinkVideoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string LogDays {
            get {
                return ResourceManager.GetString("LogDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimize_hover {
            get {
                object obj = ResourceManager.GetObject("minimize_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimize_normal {
            get {
                object obj = ResourceManager.GetObject("minimize_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimize_press {
            get {
                object obj = ResourceManager.GetObject("minimize_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ookii_Dialogs_Wpf {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs_Wpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Page_Background {
            get {
                object obj = ResourceManager.GetObject("Page_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_select {
            get {
                object obj = ResourceManager.GetObject("page_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_hover {
            get {
                object obj = ResourceManager.GetObject("play_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_normal {
            get {
                object obj = ResourceManager.GetObject("play_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_press {
            get {
                object obj = ResourceManager.GetObject("play_press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Processes_Library {
            get {
                object obj = ResourceManager.GetObject("Processes_Library", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap province_types_gold {
            get {
                object obj = ResourceManager.GetObject("province_types_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap province_types_normal {
            get {
                object obj = ResourceManager.GetObject("province_types_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap province_types_start {
            get {
                object obj = ResourceManager.GetObject("province_types_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://worldoftanks.eu/{0}/rss/news/.
        /// </summary>
        public static string RssWotEU {
            get {
                return ResourceManager.GetString("RssWotEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://worldoftanks.ru/ru/rss/news/.
        /// </summary>
        public static string RssWotRU {
            get {
                return ResourceManager.GetString("RssWotRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gdata.youtube.com/feeds/api/users/{0}/uploads.
        /// </summary>
        public static string RssYoutube {
            get {
                return ResourceManager.GetString("RssYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini.
        /// </summary>
        public static string SettingsMultipack {
            get {
                return ResourceManager.GetString("SettingsMultipack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;token&quot;: {
        ///        &quot;access_token&quot;: &quot;6ad398683640110e0d42c5a95ac7eda6c92c9962&quot;,
        ///        &quot;expires_at&quot;: 1412214576,
        ///        &quot;nickname&quot;: &quot;First_Helldar&quot;,
        ///        &quot;account_id&quot;: 2732865
        ///    },
        ///    &quot;info&quot;: {
        ///        &quot;video&quot;: true,
        ///        &quot;news&quot;: true,
        ///        &quot;multipack&quot;: true,
        ///        &quot;notification&quot;: &quot;0.0.0.0&quot;,
        ///        &quot;language&quot;: &quot;ru&quot;,
        ///        &quot;notify_link&quot;: &quot;&quot;
        ///    },
        ///    &quot;settings&quot;: {
        ///        &quot;kill&quot;: false,
        ///        &quot;force&quot;: false,
        ///        &quot;aero&quot;: false,
        ///        &quot;video&quot;: false,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettingsXML {
            get {
                return ResourceManager.GetString("SettingsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skrepka_hover {
            get {
                object obj = ResourceManager.GetObject("skrepka_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skrepka_normal {
            get {
                object obj = ResourceManager.GetObject("skrepka_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap skrepka_pressed {
            get {
                object obj = ResourceManager.GetObject("skrepka_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Sleeping_News {
            get {
                return ResourceManager.GetString("Sleeping_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap soldiers {
            get {
                object obj = ResourceManager.GetObject("soldiers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stat_perc_avgdamage {
            get {
                object obj = ResourceManager.GetObject("stat_perc_avgdamage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stat_perc_avgxp {
            get {
                object obj = ResourceManager.GetObject("stat_perc_avgxp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stat_perc_battles {
            get {
                object obj = ResourceManager.GetObject("stat_perc_battles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stat_perc_vins {
            get {
                object obj = ResourceManager.GetObject("stat_perc_vins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stat_rating {
            get {
                object obj = ResourceManager.GetObject("stat_rating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wot_emblem {
            get {
                object obj = ResourceManager.GetObject("wot_emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wot_emblem_pressed {
            get {
                object obj = ResourceManager.GetObject("wot_emblem_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.youtube.com/embed/{0}?rel=0&amp;controls=0&amp;showinfo=0.
        /// </summary>
        public static string Youtube_Preview {
            get {
                return ResourceManager.GetString("Youtube_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTankiWoT.
        /// </summary>
        public static string YoutubeChannel {
            get {
                return ResourceManager.GetString("YoutubeChannel", resourceCulture);
            }
        }
    }
}
