//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Hell_WPF_Multipack_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_Hell_WPF_Multipack_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05b877de3962048c5d1bd7cc18d4b286.
        /// </summary>
        public static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BackGeneral {
            get {
                object obj = ResourceManager.GetObject("BackGeneral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BackGeneralLine {
            get {
                object obj = ResourceManager.GetObject("BackGeneralLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string Default_Lang {
            get {
                return ResourceManager.GetString("Default_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Default_Multipack_Type {
            get {
                return ResourceManager.GetString("Default_Multipack_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipack.
        /// </summary>
        public static string Default_Settings_Priority {
            get {
                return ResourceManager.GetString("Default_Settings_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ai-rus.com.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.
        /// </summary>
        public static string DeveloperAPI {
            get {
                return ResourceManager.GetString("DeveloperAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /info/.
        /// </summary>
        public static string DeveloperInfo {
            get {
                return ResourceManager.GetString("DeveloperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/5PR4ma.
        /// </summary>
        public static string DeveloperLinkSite {
            get {
                return ResourceManager.GetString("DeveloperLinkSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /processes/.
        /// </summary>
        public static string DeveloperProcesses {
            get {
                return ResourceManager.GetString("DeveloperProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /users/.
        /// </summary>
        public static string DeveloperUsers {
            get {
                return ResourceManager.GetString("DeveloperUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /version/.
        /// </summary>
        public static string DeveloperWotVersion {
            get {
                return ResourceManager.GetString("DeveloperWotVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protanki.
        /// </summary>
        public static string INI {
            get {
                return ResourceManager.GetString("INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ionic_Zip {
            get {
                object obj = ResourceManager.GetObject("Ionic_Zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://file.theaces.ru/mods/proupdate/update.json.
        /// </summary>
        public static string JsonUpdates {
            get {
                return ResourceManager.GetString("JsonUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/Wlrh9F.
        /// </summary>
        public static string LinkNewsAll {
            get {
                return ResourceManager.GetString("LinkNewsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/LXaU7T.
        /// </summary>
        public static string LinkVideoAll {
            get {
                return ResourceManager.GetString("LinkVideoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ookii_Dialogs_Wpf {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs_Wpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProcessesLibrary {
            get {
                object obj = ResourceManager.GetObject("ProcessesLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://worldoftanks.com/en/rss/news/.
        /// </summary>
        public static string RssWotEn {
            get {
                return ResourceManager.GetString("RssWotEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://worldoftanks.ru/ru/rss/news/.
        /// </summary>
        public static string RssWotRU {
            get {
                return ResourceManager.GetString("RssWotRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gdata.youtube.com/feeds/api/users/{0}/uploads.
        /// </summary>
        public static string RssYoutube {
            get {
                return ResourceManager.GetString("RssYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini.
        /// </summary>
        public static string SettingsMultipack {
            get {
                return ResourceManager.GetString("SettingsMultipack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;pro&gt;
        ///  &lt;info video=&quot;True&quot; /&gt;
        ///  &lt;settings kill=&quot;False&quot; force=&quot;False&quot; aero=&quot;False&quot; video=&quot;Unchecked&quot; weak=&quot;False&quot; /&gt;
        ///  &lt;launcher minimize=&quot;0&quot; background=&quot;True&quot; /&gt;
        ///&lt;/pro&gt;.
        /// </summary>
        public static string SettingsXML {
            get {
                return ResourceManager.GetString("SettingsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTankiWoT.
        /// </summary>
        public static string YoutubeChannel {
            get {
                return ResourceManager.GetString("YoutubeChannel", resourceCulture);
            }
        }
    }
}
