using System;
using System.Collections.Generic;
using System.Windows.Forms;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Processes
{
    public class Range
    {
        public string Name, Description;
        public Range(string mName, string mDescription) { Name = mName; Description = mDescription; }
        public Range() { Name = ""; Description = ""; }
    }

    public class Listing
    {
        public string mName, mDescription;
        public List<Range> List;
        public List<List<Range>> subRange;

        public void Add(string name, string description)
        {
            try { if (List.Count <= 0) { } }
            catch (Exception)
            {
                List = new List<Range>();
                subRange = new List<List<Range>>();
            }

            List.Add(new Range(name, description));
            subRange.Add(List);

            mName = subRange[0][0].Name;
            mDescription = subRange[0][0].Description;
        }

        public List<Range> View()
        {
            return List;
        }

        public void Clear()
        {
            try { List.Clear(); }
            catch (Exception) { }
        }

        public bool IndexOf(string str)
        {
            try
            {
                foreach (var pr in List)
                    if (pr.Name == str) return true;
                return false;
            }
            catch (Exception) { return false; }
        }

        public int Count()
        {
            try { return List.Count; }
            catch (Exception) { return 0; }
        }
    }

    public class Global
    {
        public bool Search(string process)
        {
            try
            {
                foreach (string proc in Processes())
                    if (proc == process) return true;
            }
            catch (Exception) { return false; }

            return false;
        }

        public Array Processes()
        {
            string[] vipProcess = {
                Process.GetCurrentProcess().ProcessName.ToString(),
                "Multipack Launcher.vshost",
                "s",
                "s.bat",
				"restart",
				"WorldOfTanks",
				"WoTLauncher",
"1cv7l",
"1cv8",
"1cv8c",
"360rp",
"360sd",
"360sdupd",
"360Tray",
"360webshield",
"3G HSDPA Modem",
"3G Internet",
"3G life modem",
"3G Modem Manager",
"3yuar0ib",
"AAWTray",
"ACFanControl",
"ACU",
"ACWLIcon",
"Ad-Aware",
"Ad-AwareAdmin",
"adawarebp",
"AdAwareTray",
"Adblock",
"AdBlock.Agent",
"ADBlockerTray",
"Adguard",
"AdMunch",
"admunch",
"AdMunch64",
"AdMuncherUpdater",
"AdStopperTrayApp",
"ah",
"AIMP2",
"AIMP2Portable",
"AIMP3lib",
"Air Mouse",
"AirDisplay",
"AirGCFG",
"AirNCFG",
"ANTIVIRЬ",
"AnVir",
"anvir64",
"AnVir64",
"ApUI",
"ApVxdWin",
"AsFnControl",
"ashDisp",
"ASUS Console Starter",
"ASUS Docking",
"AsusAudioCenter",
"ASUSManager",
"AsusTPCenter",
"AsusTPHelper",
"AsusTPLauncher",
"AsusTPLoader",
"asusUPCTLoader",
"AsusWSPanel",
"AsusWSService",
"ASUSxGPU-Z",
"Ati2evxx",
"atibtmon",
"atidimsvc",
"atitray",
"avast.setup",
"avastui",
"avcenter",
"avciman",
"avcom",
"avgcfgex",
"AVGIDSMonitor",
"avgmfapx",
"avgnt",
"avgtray",
"avgui",
"avg_tuht_stf_all_2014_423",
"Avira.OE.Systray",
"avira_system_speedup",
"AVKTray",
"AvP",
"Beeline Helper",
"Beeline Home Internet",
"Beeline Internet at Home",
"Black",
"Boingo Wi-Fi",
"Boost",
"boostspeed",
"BoostSpeed",
"BoostSpeedPortable",
"BOOSTS~1",
"cAIMP",
"CCP",
"ccSvcHst",
"ccsvchst",
"cfp",
"cis",
"cistray",
"CisTray",
"clamscan",
"ClamTray",
"CLI",
"Client",
"client3",
"CLIStart",
"cmd64",
"cmmon32",
"ComUpdatus",
"ControlCenter",
"ControlCenter_Side",
"cooling",
"Core Temp",
"CORE TEMP",
"Core Temp_x64",
"CoreTemp64",
"CpuLevelUpHook32",
"CpuLevelUpHook64",
"CpuLevelUpHookLaunch",
"CpuPowerMonitor",
"DeLay",
"dinotify",
"DM2",
"DoScan",
"dragon",
"DriverAP",
"drwagnui",
"DRWAGNUI",
"DWHWizrd",
"DWRCC",
"DWRCST",
"dwscanner",
"eeclnt",
"evaer",
"FamItrf2",
"fancontroller",
"FanHelp",
"frwl_notify",
"FRWL_NOTIFY",
"fshoster32",
"FSM32",
"gbtray",
"GdBgInx64",
"GeForce_Experience_v2.1.0.0",
"GFExperience",
"H3GMS",
"H760",
"H800",
"HDAudioCPL",
"Hid",
"hkcmd",
"Hotkey",
"hotkey",
"HotkeyApp",
"HotKeyb",
"Hotkeycontrol",
"HotKeyOSD",
"HotkeyUtility",
"HPKEYBOARDx",
"hpMonitor21",
"hpMonitor23",
"HPMSGSVC",
"HPWAMain",
"HPWA_Main",
"HSPA USB MODEM",
"HSSCP",
"HUAWEI Modem",
"HUAWEI Modem 2.0",
"HUAWEI Modem Fon",
"HUAWEI Modem Live",
"HUAWEI Modem Micro",
"HUAWEI Modem Mini",
"HUAWEI Modem Plus",
"Huawei3GModemSoftware",
"HuaweiModemSoftware",
"HUD",
"IMF",
"IMhid",
"InstStub",
"KLM",
"KMCONFIG",
"kss",
"kxetray",
"LachesisSysTray",
"LAN Manager",
"MacsFanControl",
"mbae",
"mbam",
"mbamgui",
"mcagent",
"McPvTray",
"McTray",
"McUICnt",
"mcupdate",
"mcupdui",
"McVsShld",
"Mouse",
"MouseCamera",
"MouseDrv",
"mousehid",
"MouseKeyboardCenterx64_1049",
"MouseServer",
"MouseTracer",
"MRT",
"mywifi",
"MzCPUAccelerator",
"MzGameAccelerator",
"MzRAMBooster",
"nanoav",
"NAT",
"nav",
"NAV",
"Net4Switch",
"NetAnimate",
"netsession_win",
"netsetman",
"NetSph",
"NetTraffic",
"netview",
"NetworkClient",
"NetworkGenie",
"NetworkIndicator",
"NetworkIndicator_RUS",
"NetworkManager",
"networx",
"NetWorx",
"nis",
"NIS",
"NOBuClient",
"nod32egui",
"nod32kernel.dat",
"nspmain",
"NST",
"nst",
"nto",
"nTuneCmd",
"nusb3mon",
"NVBACK~1",
"NvCplSetupInt",
"nvcplui",
"nvidiaInspector",
"NVIDIAOCAP",
"NvLedServiceHost",
"NVMonitor",
"nvraidservice",
"nvsmartmaxapp",
"nvspcaps",
"nvspcaps64",
"NVTray",
"nvwmi64",
"NWD2105",
"NWD2205",
"osk",
"OverclockingCenter",
"OverwolfBrowser",
"OverwolfHelper",
"OverwolfHelper64",
"OverwolfLauncher",
"OverwolfTeamSpeakInstaller",
"Panda_URL_Filtering",
"ProtectionUtilSurrogate",
"Rambooster",
"RaUI",
"RAVBg64",
"RAVCpl64",
"Razer Barracuda AC-1 Gaming Audio card",
"RazerAnansiSysTray",
"RazerCore",
"razerhid",
"RazerImperatorTray",
"RazerIngameEngine",
"RazerMambaSysTray",
"RazerNagaSysTray",
"RazerNostromoSysTray",
"razerofa",
"RazerOrochiTray",
"RazerStarCraftIISysTray",
"razertra",
"rbmonitor",
"RBTray",
"RCHotKey",
"RDVCHG",
"RtDCpl64",
"RTFTrack",
"RTHDCPL",
"RtHDVBg",
"RtHDVCpl",
"RtkBtMnt",
"RtkNGUI",
"RtVOsd",
"RTVOSD64",
"RtWLan",
"RtWlan",
"rundll32",
"RunUSBGuard",
"rusb3mon",
"Ryos MK Monitor",
"RzCefRenderProcess",
"RzCommsInGameApplet",
"RzSynapse",
"SecGu",
"SecureAPlus",
"SecureCRT",
"SecureEraseDropAgent",
"Skype.exe.exe",
"SkypePlugin",
"skypePM",
"SkypePortable",
"SOUNDMAN",
"soundman",
"SoundMAX",
"SoundMAX",
"soundrec",
"SoundTray",
"SoundWireServer",
"SpywareTerminatorShield",
"SpywareTerminatorUpdate",
"sqlmangr",
"sqlservr",
"stpass",
"ts3server_win32",
"ts3server_win64",
"TUSBAudioCpl",
"TWCU",
"wcourier",
"WiFi GO! Server",
"WiFi HotSpot Creator",
"WiFiCreator",
"WiFiGuard",
"WiFileTransfer",
"WifiManager",
"WiFiMsg",
"WiMAXCU",
"Wireless",
"Wireless Broadband",
"wirelesscm",
"WirelessManager",
"WirelessModem",
"WiseGameBooster",
"WiseMemoryOptimzer",
"WiseRegCleaner",
"WiseTray",
"WLAN Optimizer",
"WLanGUI",
"WlanMgr",
"WlanUtility",
"WLAN_Service",
"Adguard",
"AI Suite II",
"AIMP3",
"AirGCFG",
"AllShareAgent",
"AnVir",
"AsRoutineController",
"atieclxx",
"AvastUI",
"avastui",
"avgnt",
"avgui",
"avp",
"avpui",
"avscan",
"breakaway",
"BtvStack",
"ccApp",
"CCC",
"ccSvcHst",
"cis",
"cistray",
"Cloud",
"cmd",
"conhost",
"CoolSense",
"csrss",
"csrss",
"DCSHelper",
"devenv",
"dllhost",
"Dropbox",
"drwagnui",
"DTShellHlp",
"dwm",
"dwm",
"egui",
"explorer",
"FamItrfc",
"fraps",
"GitExtensions",
"GPUTweak",
"HPMSGSVC",
"HPOSD",
"htcUPCTLoader",
"HydraDM",
"icq",
"ICQ",
"InputPersonalization",
"IntelliTrace",
"iusb3mon",
"jusched",
"magent",
"ManagerCryptoFS",
"mbamgui",
"MKey",
"MKey",
"MOM",
"MOM",
"Mouse",
"MSIAfterburner",
"msseces",
"NetiCtrlTray",
"NetMap",
"NetSph",
"NetSvcHelp",
"nis",
"nusb3mon",
"NvBackend",
"NvBackend",
"nvstreamsvc",
"NvTmru",
"nvtray",
"nvvsvc",
"NvXDSync",
"nvxdsync",
"Overwolf",
"plugin-nm-server",
"qip",
"QuickGesture",
"RaidCall",
"raidcall",
"RaUI",
"RazerImperatorSysTray",
"RazerNagaSysTray",
"RtHDVCpl",
"RtkNGUI64",
"RtWLan",
"rundll32",
"RzSynapse",
"ScreenCapture",
"Skype",
"Skype ",
"SmcGui",
"SoundMAX",
"taskeng",
"taskhost",
"taskhostex",
"ts3client_win32",
"ts3client_win64",
"U3BoostSvr32",
"U3BoostSvr64",
"USBGuard",
"VDeck",
"Viber",
"VolCtrl",
"Volume2",
"wcourier",
"WiFileTransfer",
"winamp",
"winlogon",
"WoTLogger3",
"WWAHost",
"xPopups",
"xStarter",
"xStartUI",
"YandexDisk",
"YCMMirage"
            };

            return vipProcess;
        }
    }
}
